# .github/workflows/ci.yml

name: Node.js CI

# This workflow runs on every push and pull request to the main branch
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use the Node.js version you are targeting

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the specified version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install all dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the linter to check for code style issues
      - name: Run linter
        run: npm run lint

      # Step 5: Run all automated tests
      # The --ci flag is often used to optimize test runs for CI environments
      - name: Run tests
        run: npm test -- --ci --passWithNoTests

      # Step 6: Run a security audit for production dependencies
      - name: Run security audit
        run: npm audit --production --audit-level=moderate